### ISSUE TITLE
Deprecated Constant used

### ISSUE THREAD

**Issue by flle** [Superkikim/maxsmart#1]
Hi,

stumbled accross this message for the maxsmart integration in my Home Assisstant log:
DEVICE_CLASS_POWER was used from maxsmart, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER instead, please report it to the author of the 'maxsmart' custom integration

I am not really familiar with HA integrations to fix it myself so I do as proposed and inform the author :-).
Would be nice if this can be fixed until 25.01.
Thanks for providing this integration works really well for me.

**Comment by Superkikim** [comment]
Hi. You are on the python module repo here. Not the integration. 

I'm currently refactoring the module. Next I will be refactoring the integration. Please be kind enough to close this issue and open the same on at https://github.com/Superkikim/mh-maxsmart-hass/issues. I'll take care of this.

Thank you
